name: Build and deploy website to Azure Web App - GeoffreyCodeMusic

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Build the website
        run: npm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: Geoffreycodewebsitefiles

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: 47fc0454-6560-4e4a-b0c7-7dab47e1f96c
          tenant-id: 4eef7cd3-2305-43d4-9547-f37d4af3a462
          subscription-id: 27da48e1-e85a-47dc-8b04-9b2ae49ac97e
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'Geoffreycodemusician'
          slot-name: 'Production'
          package: Geoffreycodewebsitefiles
